### ISSUE TITLE
Weather not loading

### ISSUE THREAD

**Issue by EMH333** [laedit/new-tab-moment#65] opened 2020-01-21 18:17 UTC
I have the add-on set to load weather from location automatically, however it recently changed to just 3 loading dots and the console gives this error: `uncaught exception: Object`

I am not sure how long ago this started but I know it was since the new year if not in the past week or so.

I would be happy to provide more details if needed

**Comment by laedit** [comment] 2020-01-22 02:22
Thanks for the issue!
Sadly I can't reproduce it.
Could you check that if you set a city explicitely the issue does not appear?
What unit have you selected?
Also could you tell me the browser you use and his version?
Does the console provide a line number?
Thanks!

**Comment by EMH333** [comment] 2020-01-22 05:16
Firefox 72.0.1
Selected Celsius units
Console does not provide a line number (this is one of the first times I have seen something like this)
Selecting a city does appear to fix the issue (the weather shows up and the console error does not appear)
Oddly the console error shows up at least a half second after the page finishes loading. Sometimes up to two seconds after.
![Screenshot from 2020-01-21 21-05-31](https://user-images.githubusercontent.com/13910070/72867236-1e093380-3c93-11ea-9ab3-519a49a96364.png)

**Comment by laedit** [comment] 2020-01-22 13:14
Thanks for the info.
I think that the call to openweathermap.org fails with your geolocation.
I will add some traces as soon as I have the time, but I don't know if I can resolve this...
Just to be sure, does the extension have the permission to use the geolocation?

**Comment by laedit** [comment] 2020-01-22 13:17
If your are familiar with Firefox Dev Tools (accessible by pressing F12), could you open a new tab, press F12, go to the network tab and click reload?
This will reload the page and normally display the request to openweathermap.
If the request is displayed, could you right-click on it and save as HAR and add the HAR file in this issue?
Thanks a lot!

**Comment by EMH333** [comment] 2020-01-22 18:18
To confirm the location permission, I disallowed the extension from geolocation, then enabled it when it asked for it again on the next reload. No change unfortunately. 

There is no request being sent. When I manually enter a city, I can see a request to the OWM endpoint but I see no network activity when attempting to geolocate.

I am curious if this is related to privacy stuff Firefox recently added, I might play around and see if that makes a difference

**Comment by laedit** [comment] 2020-01-23 08:21
Sorry, I forgot a part before reload the page to check the request: can you go to the Storage tab and delete all items in the local storage first?
This will delete the cextensions's cache and a request will be sent.

**Comment by EMH333** [comment] 2020-01-23 18:39
Deleted local storage for the extension, reloaded page and still having the same issue, nothing appeared to change :/

I am going to reinstall the extension and see if that changes anything

**Comment by laedit** [comment] 2020-01-24 08:09
Weird, it seems that the error is coming from `navigator.geolocation.getCurrentPosition`.
I will add some traces and catch to be sure this week-end.

**Comment by laedit** [comment] 2020-01-26 15:19
The new version (0.5.1) is up, can you upgrade your local version, activate the debug mode in the options and check the console on a new tab?
Thanks!

**Comment by laedit** [comment] 2020-01-27 16:00
I have checked on the firefox at work (68.4.1esr) and got a "navigator.geolocation is undefined" error when using new tabt moment without location.
On [CanIUse](https://caniuse.com/#search=geolocation) it seems that the corrdinates part of geolocation api had an absence during the 71 version of firefox (and I guess 68 esr), so it should not be your issue but I think I will explicit this error.

**Comment by EMH333** [comment] 2020-01-29 01:15
Yeah it looks like my issue is a personal problem, not tied to this extension. No other websites could find my location (I should have tried that first, my bad). I guess I need to work my way up the food chain...

![Screenshot from 2020-01-27 13-03-22](https://user-images.githubusercontent.com/13910070/73319419-2ad8da80-41f1-11ea-83a5-2a3975407d07.png)

**Comment by laedit** [comment] 2020-01-29 08:34
At least it made me add some necessary traces and checks :)
Have you tried to restart firefox without addons?
Or to reinstall it?

**Comment by laedit** [comment] 2020-02-06 09:58
I have release a new version of the addon which better handle weather and geolocation errors, I will now close this issue, thanks again for opening it! :)
For your problem, through my search on the subject I have found that it is possible to delete or override some key configuration on geolocation like these one on `about:config`: `geo.wifi.uri`, default value `https://www.googleapis.com/geolocation/v1/geolocate?key=%GOOGLE_LOCATION_SERVICE_API_KEY%`.

**Closed by laedit** 2020-02-06 09:58 UTC
